### ISSUE TITLE
Include ndlml library?

### ISSUE THREAD

**Issue by cemoody** [SheffieldML/collab#1]
Hi,
I've been looking over this code and it looks amazing -- but could you include the ndlml library? The Python files seem to require it. We're quite interested in using GPs in collaborative filtering, but would like to try a quick example before getting too invested. 

Many thanks!
chris

**Comment by sschnug** [comment]
I second that request.

**Comment by lawrennd** [comment]
Chris,

Apologies for missing your original post! I'll look into releasing it when
I'm back although the code was my first foray into python so may be a bit
ugly! I'll see if I can dog or out, about to fly back from NYC. Please
prompt me again if I forget.

Neil

**Comment by lawrennd** [comment]
Hi Both,

I've just added the ndlml library as a submodule. Unfortunately I can't compile it on this OSX machine I have access to at the moment, so it's untested. I got as far as doing the compilation of the swig, that worked OK, but then there was a missing library on the local machine. 

Let me know how you get on with it, and feel free to submit pull requests if you need to edit to get things working!

Neil
